name: cicd

on:
  pull_request:
  push:
    branches: 
    tags:

jobs:
  checkout_refs:
    runs-on: ubuntu-20.04
    steps:
      - name: Expose useful environment variables
        uses: FranzDiebold/github-env-vars-action@v1.3.0
      - name: Tag docker image
        run: echo "Docker image tag is registry/owner/repo/image:${GITHUB_REF_NAME}"
